# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mokumoku_onlie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for mokumoku_onlie

  target 'mokumoku_onlieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mokumoku_onlieUITests' do
    # Pods for testing
  end

end
